
const laptopProducts = [
    { id: 1, productName: 'Dell Inspiron 15', price: 45000, ratings: 4.5, discount: '35%', availability: 'Available', image: './images/2.jpeg' },
    { id: 2, productName: 'HP Pavilion x360', price: 55000, ratings: 4.2, discount: '20%', availability: 'Available', image: './images/1.png' },
    { id: 3, productName: 'Lenovo ThinkPad X1', price: 75000, ratings: 4.7, discount: '25%', availability: 'Available', image: './images/1.png' },
    { id: 4, productName: 'Asus ZenBook 14', price: 62000, ratings: 4.6, discount: '15%', availability: 'Out of Stock', image: './images/3.jpg' },
    { id: 5, productName: 'Acer Aspire 7', price: 48000, ratings: 4.3, discount: '10%', availability: 'Available', image: './images/1.png' },
    { id: 6, productName: 'Microsoft Surface Laptop', price: 65000, ratings: 4.4, discount: '18%', availability: 'Available', image: './images/2.jpeg' },
    { id: 7, productName: 'Apple MacBook Air', price: 92000, ratings: 4.8, discount: '12%', availability: 'Available', image: './images/4.jpg' },
    { id: 8, productName: 'Dell XPS 13', price: 85000, ratings: 4.6, discount: '22%', availability: 'Available', image: './images/1.png' },
    { id: 9, productName: 'HP Envy 13', price: 70000, ratings: 4.5, discount: '30%', availability: 'Available', image: './images/3.jpg' },
    { id: 10, productName: 'Lenovo IdeaPad 3', price: 35000, ratings: 4.1, discount: '28%', availability: 'Available', image: './images/4.jpg' },
    { id: 11, productName: 'Asus TUF Gaming A15', price: 55000, ratings: 4.2, discount: '10%', availability: 'Available', image: './images/2.jpeg' },
    { id: 12, productName: 'MSI GF63 Thin', price: 50000, ratings: 4.3, discount: '25%', availability: 'Available', image: './images/4.jpg' },
    { id: 13, productName: 'Apple MacBook Pro 16', price: 160000, ratings: 4.9, discount: '8%', availability: 'Available', image: './images/1.png' },
    { id: 14, productName: 'Dell Latitude 7420', price: 90000, ratings: 4.6, discount: '20%', availability: 'Available', image: './images/1.png' },
    { id: 15, productName: 'HP Spectre x360', price: 70000, ratings: 4.4, discount: '15%', availability: 'Available', image: './images/1.png' },
    { id: 16, productName: 'Lenovo Legion 5', price: 75000, ratings: 4.7, discount: '22%', availability: 'Available', image: './images/1.png' },
    { id: 17, productName: 'Acer Swift 3', price: 45000, ratings: 4.3, discount: '30%', availability: 'Available', image: './images/1.png' },
    { id: 18, productName: 'Asus ROG Zephyrus G14', price: 90000, ratings: 4.8, discount: '10%', availability: 'Available', image: './images/1.png' },
    { id: 19, productName: 'Dell G5 15', price: 60000, ratings: 4.4, discount: '20%', availability: 'Available', image: './images/3.jpg' },
    { id: 20, productName: 'HP Omen 15', price: 67000, ratings: 4.6, discount: '18%', availability: 'Available', image: './images/3.jpg' },
    { id: 21, productName: 'Lenovo Yoga 7i', price: 65000, ratings: 4.5, discount: '25%', availability: 'Available', image: './images/4.jpg' },
    { id: 22, productName: 'Asus VivoBook 15', price: 38000, ratings: 4.2, discount: '28%', availability: 'Available', image: './images/2.jpeg' },
    { id: 23, productName: 'MSI Prestige 14', price: 70000, ratings: 4.5, discount: '12%', availability: 'Available', image: './images/1.png' },
    { id: 24, productName: 'Apple MacBook Pro 13', price: 105000, ratings: 4.7, discount: '15%', availability: 'Available', image: './images/3.jpg' },
    { id: 25, productName: 'Dell Inspiron 14', price: 42000, ratings: 4.4, discount: '20%', availability: 'Available', image: './images/1.png' },
    { id: 26, productName: 'HP Pavilion 14', price: 50000, ratings: 4.3, discount: '22%', availability: 'Available', image: './images/1.png' },
    { id: 27, productName: 'Lenovo ThinkPad T14', price: 78000, ratings: 4.6, discount: '18%', availability: 'Available', image: './images/1.png' },
    { id: 28, productName: 'Asus ExpertBook B9', price: 87000, ratings: 4.7, discount: '10%', availability: 'Available', image: './images/4.jpg' },
    { id: 29, productName: 'Acer Nitro 5', price: 62000, ratings: 4.4, discount: '25%', availability: 'Available', image: './images/3.jpg' },
    { id: 30, productName: 'Microsoft Surface Pro 7', price: 80000, ratings: 4.5, discount: '20%', availability: 'Available', image: './images/2.jpeg' },
    { id: 31, productName: 'Apple MacBook Air M2', price: 95000, ratings: 4.8, discount: '12%', availability: 'Available', image: './images/3.jpg' },
    { id: 32, productName: 'Dell XPS 15', price: 95000, ratings: 4.6, discount: '22%', availability: 'Available', image: './images/4.jpg' },
    { id: 33, productName: 'HP Envy 17', price: 75000, ratings: 4.4, discount: '18%', availability: 'Available', image: './images/2.jpeg' },
    { id: 34, productName: 'Lenovo Legion 7i', price: 85000, ratings: 4.7, discount: '25%', availability: 'Available', image: './images/1.png' },
    { id: 35, productName: 'Asus ZenBook Flip 14', price: 68000, ratings: 4.5, discount: '15%', availability: 'Available', image: './images/1.png' },
    { id: 36, productName: 'MSI Creator 15', price: 93000, ratings: 4.6, discount: '10%', availability: 'Available', image: './images/1.png' },
    { id: 37, productName: 'Apple MacBook Pro 14', price: 120000, ratings: 4.9, discount: '8%', availability: 'Available', image: './images/3.jpg' },
    { id: 38, productName: 'Dell Latitude 5510', price: 78000, ratings: 4.4, discount: '20%', availability: 'Available', image: './images/2.jpeg' },
    { id: 39, productName: 'HP Spectre 13', price: 69000, ratings: 4.5, discount: '15%', availability: 'Available', image: './images/4.jpg' },
    { id: 40, productName: 'Lenovo IdeaPad Flex 5', price: 55000, ratings: 4.3, discount: '22%', availability: 'Available', image: './images/1.png' },
    { id: 41, productName: 'Asus ROG Flow X13', price: 90000, ratings: 4.6, discount: '20%', availability: 'Available', image: './images/3.jpg' },
    { id: 42, productName: 'Acer Aspire 5', price: 42000, ratings: 4.2, discount: '25%', availability: 'Available', image: './images/1.png' },
    { id: 43, productName: 'Microsoft Surface Laptop Go', price: 65000, ratings: 4.4, discount: '18%', availability: 'Available', image: './images/4.jpg' },
    { id: 44, productName: 'Apple MacBook Air 2021', price: 87000, ratings: 4.7, discount: '12%', availability: 'Available', image: './images/2.jpeg' },
    { id: 45, productName: 'Dell Inspiron 16', price: 56000, ratings: 4.3, discount: '30%', availability: 'Available', image: './images/1.png' },
    { id: 46, productName: 'HP Pavilion Gaming 15', price: 58000, ratings: 4.4, discount: '20%', availability: 'Available', image: './images/4.jpg' },
    { id: 47, productName: 'Lenovo ThinkBook 14', price: 49000, ratings: 4.2, discount: '28%', availability: 'Available', image: './images/1.png' },

]
export default laptopProducts;
